### ISSUE TITLE
Question: Overlay logo & performance comparison

### ISSUE THREAD

**Issue by alexanderadam** [spider-gazelle/qr-code#1]
Hi Stephen,

just to be sure: it is currently not possible to add an overlay logo to the QR code, right?
And is there any chance that you made a benchmark with a comparison to this [Go implementation](https://github.com/divan/qrlogo)?

Thank you so much for your Crystal Shards! 🙏

**Comment by stakach** [comment]
haven't benchmarked it, it's fast compared to ruby lol
In terms of the PNG image, you could generate the QR code PNG and then overlay an image using [stumpy_png](https://github.com/stumpycr/stumpy_png) probably not too hard

and you could have colour overlays unlike the GO version

**Comment by alexanderadam** [comment]
Wow, thank you for your incredibly fast response!

In our case performance in combination with the the overlay is the _major_ concern. Switzerland got [a standard for QR codes on invoices with the Swiss cross in the centre](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf) (everything only in black and white, though):

<div align = "center">

![Swiss QR Code](https://user-images.githubusercontent.com/372620/112961279-82e8d500-9145-11eb-8713-b9b7fe5f83d3.png)

</div>


Ruby implementations are _unacceptable_ slow for this and the mentioned Go implementation can generate over thousand of such QR codes in roughly 40 seconds whereas [this (admittedly unoptimized) Ruby implementation](https://github.com/damoiser/qr-bills/#notes) takes more than ten minutes.

This is the particular reason why I'm curious how this shard would compare to that.
But in this case I know that this shard is most probably not suitable yet.

Again, thank you so for your work and your fast response!

**PS:** Please ping me in case you're doing a benchmark at one point! 😉

**Comment by stakach** [comment]
this implementation probably generates QRs at a similar speed to GO - just haven't benchmarked

**Comment by russ** [comment]
I was trying to figure out how to do this and came up with the following. Adding it here just in case anyone else is trying to do the same.

```
require "qr-code"
require "qr-code/export/png"
require "http/client"
require "pixie"
require "stumpy_utils"

include StumpyPNG

size = 512
logo_size = (size * 0.15).ceil.to_i
border_size = 20 + logo_size

mask_canvas = Canvas.new(logo_size, logo_size, RGBA::BLACK)
mask_canvas.circle(logo_size // 2, logo_size // 2, logo_size // 2, RGBA::WHITE, true)
mask_io = IO::Memory.new
StumpyPNG.write(mask_canvas, mask_io)
mask_io.rewind
mask_image = Pixie::Image.new(mask_io)
mask_image.set_alpha(:copy)

logo_image = HTTP::Client.get("https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/220px-SpongeBob_SquarePants_character.svg.png").body
logo_image = Pixie::Image.new(logo_image.to_slice)
logo_image.resize(logo_size, logo_size)
logo_image.composite(mask_image, :copy_alpha, :center)

border_mask_canvas = Canvas.new(border_size, border_size)
border_mask_canvas.circle(border_size // 2, border_size // 2, border_size // 2, RGBA::WHITE, true)
border_mask_io = IO::Memory.new
StumpyPNG.write(border_mask_canvas, border_mask_io)
border_mask_io.rewind
border_mask_image = Pixie::Image.new(border_mask_io)
border_mask_image.set_alpha(:copy)

qr = QRCode.new("https://google.com/").as_png(size: size)
qr_image = Pixie::Image.new(qr.to_slice)
qr_image.set_alpha(:copy)
qr_image.composite(border_mask_image, :over, :center)
qr_image.composite(logo_image, :over, :center)
qr_image.write("qr_code.png")
```
